spring.application.name=pipeline
 # THIS IS THE BRIDGE THAT CONNECTS THE POSTGRESQL DATABASE TO THE SPRING BOOT APPLICATION 

 # Server Port Configuration
server.port=8080

# Database Connection (Pointing to local Docker container)
spring.datasource.url=jdbc:postgresql://localhost:5432/fitsync_db
spring.datasource.username=developer
# this should work for the password (I will add this to the .gitignore or let the password live in docker). I will come back to this
spring.datasource.password=sweinternlocked
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# "validate" ensures Spring honors the explicit schema.sql instead of overwriting it. I am replacing validate with update so that 
# tables that don't exist yet can be created in the postgreSQL database (to not through errors)
spring.jpa.hibernate.ddl-auto=update 
# for debugging:
spring.jpa.show-sql=true 
